
server:
  port: 8761

spring:
  application:
    name: service-rigistry

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-rigistry: false
    serviceUrl:
      defaultZone: http://@{eureka.instance.hostname}:${server.port}/eureka/}

